channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-yaml=2.3.12
  - conda-forge::r-ggplot2=4.0.1
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-stringr=1.6.0
  - bioconda::bioconductor-gsva=2.0.0
  - bioconda::bioconductor-singscore=1.26.0
  - conda-forge::r-factominer=2.13.0
  - conda-forge::r-tibble=3.3.1
  - conda-forge::r-matrixstats=1.5.0
